@startuml
left to right direction
skinparam packageStyle rect
actor менеджер
actor кладовщик
actor оператор
rectangle ИС {
  оператор --> (поступление)
  оператор --> (уход со склада)
  оператор --> (списание товара)
  оператор --> (инвентаризация)
  менеджер --> (поступление)
  менеджер --> (уход со склада)
  кладовщик --> (инвентаризация)
  кладовщик --> (списание товара)
  кладовщик --> (место нахождения)
  (списание товара) .> (уход со склада)
  (инвентаризация) .> (место хранения)
}

@enduml


#классы

@startuml
class поступление{
 +код поставки
 +код поставщика
 +код менеджера
 +дата поставки
 +наименование товара
}
class инвентаризация{
 +код инвентаризации(число)
 +время(дата/время)
 +описание(текст)
 +код работника(число)
}

class место_хранения{
+код стеллажа
+вместимость
+категория
+номер ячейки стеллажа
}
class работники{
+код пользователя
+ФИО
+логин
+пароль
+роль
}
class продажа{
+количество покупки
+возврат
}
class уход_со_склада{
+код списания
+количество
+дата/время
}


поступление <.. работники
инвентаризация <.. работники
продажа <.. работники
место_хранения <.. инвентаризация
продажа <.. поступление
уход_со_склада <.. работники
инвентаризация <.. уход_со_склада
продажа <.. инвентаризация
продажа <.. место_хранения
@enduml

#последовательность

@startuml
participant Заказ_и_распределение_товара as Foo
actor       Оператор    as Foo1
actor       Менеджер    as Foo6
actor       Кладовщик    as Foo7
participant    Заказ    as Foo2
participant    поступление     as Foo3
participant      Инвентаризация      as Foo4
participant    Место_хранения   as Foo5


Foo1 -> Foo6 : Получение задания
Foo1 -> Foo2 : оформление заявки
Foo2 -> Foo3 : На склад
Foo6 -> Foo4 : распределение
Foo4 -> Foo7 : задание кладовщику
Foo7 -> Foo5 : Распредение на конечную точку

@enduml
```
